generalHomeMenu:
  path: /menu/home-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\HomeController' }

generalProjectsMenu:
  path: /menu/projects-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\ProjectsController' }

generalIssusMenu:
  path: /menu/issues-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\IssuesController' }

generalReportsMenu:
  path: /menu/filters-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\FiltersController' }

generalAgileMenu:
  path: /menu/agile-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\AgileController' }

generalHelpDeskMenu:
  path: /menu/helpdesk-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\HelpDeskController' }

generalDocumentadorMenu:
  path: /menu/documentator-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\DocumentadorController' }

generalSVNMenu:
  path: /menu/svn-menu
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\Menu\SVNController' }

generalHome:
  path: /general-settings/home
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\IndexController' }

generalLog:
  path: /general-settings/logs/{from}/{to}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\LogController' }

generalUsers:
  path: /general-settings/users
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\ListUserController' }

generalUsersProfileManager:
  path: /general-settings/users/profile-manager
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\ListProfileCategoryController' }

generalUsersProfileManagerAddCategory:
  path: /general-settings/users/profile-manager/category/add
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\AddProfileCategoryController' }

generalViewGeneral:
  path: /general-settings/view-general
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\ViewGeneralController' }

generalViewSMTPSettings:
  path: /general-settings/smtp-settings
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\SMTP\ViewController' }

generalEditSettings:
  path: /general-settings/edit-general
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\EditSettingsController' }

generalMailQueue:
  path: /general-settings/main-queue
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\MailQueueController' }

generalEditUser:
  path: /general-settings/users/edit/{id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\EditController' }
  requirements:
    id:  \d+

generalAddUser:
  path: /general-settings/users/add
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\AddController' }

generalDeleteUserConfirm:
  path: /general-settings/delete-user-confirm/{user_id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\DeleteConfirmController' }
  requirements:
    user_id:  \d+

generalDeleteUser:
  path: /general-settings/delete-user
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\DeleteController' }

generalUserUpdatePreferencesConfirm:
  path: /user/update-preferences-dialog/{id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\UpdatePreferencesConfirmController' }

generalUserUpdatePreferences:
  path: /user/update-preferences
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\UpdatePreferencesController' }

generalChnagePasswordConfirm:
  path: /general/user/change-password-dialog/{user_id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\ChangePasswordConfirmController' }

generalChangePassword:
  path: /general/user/change-password
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\User\ChangePasswordController' }

generalAbout:
  path: /ubirimi/about
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\AboutController' }

generalSMTPDeleteConfirm:
  path: /general-settings/delete-smtp-server-confirm/{id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\SMTP\DeleteConfirmController' }

generalSMTPDelete:
  path: /general-settings/delete-smtp-server
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\SMTP\DeleteController' }

generalSMTPAdd:
  path: /general-settings/smtp-settings/add
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\SMTP\AddController' }

generalSMTPEdit:
  path: /general-settings/smtp-settings/edit/{id}
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\SMTP\EditController' }

generalFeedbackConfirm:
  path: /send-feedback-dialog
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\FeedbackConfirmController' }

generalFeedback:
  path: /send-feedback
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\FeedbackController' }

generalKeyboardShortcuts:
  path: /keyboard-shortcuts-dialog
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\KeyboardShortcutsController' }

generalRefreshTimezone:
  path: /general-settings/refresh-timezone
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\RefreshTimezoneController' }

generalAccessDenied:
  path: /general-settings/bad-link-access-denied
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\AccessDeniedController' }

generalManageApplications:
  path: /general-settings/applications/manage
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\ManageApplicationsController' }

generalManageAppList:
  path: /general-settings/update-app-list
  defaults: { _controller: '\Ubirimi\GeneralSettings\Controller\ManageAppListController' }
